#!/usr/bin/guile
!#

(add-to-load-path (string-append (getcwd) "/dynamic/modules"))
(import (sph web app) (sph-info))
(swa-start swa-app (string-append (getcwd) "/dynamic")
  "production" swa-server-scgi #:parse-query #t)
