#!/usr/bin/guile
!#

(add-to-load-path (string-append (getcwd) "/modules"))
(import (sph) (sph web app) (sph-info))

(apply
  (l* (#:optional (config "production"))
    (swa-start swa-app (string-append (getcwd) "/dynamic") config swa-server-scgi #:parse-query #t))
  (tail (program-arguments)))
